### ISSUE TITLE
Update Experiment page

### ISSUE THREAD

**Issue by auggiemarignier** [upflow-eu/upflow-eu.github.io#85]
Update all the text to clearly distinguish the 2021 and 2022 expeditions (e.g., refer to the 2021 expedition as past rather than future...). Update Team (clearly identify those who attended 2021 expedition vs 2022 expedition)

**Comment by auggiemarignier** [comment]
@mary-tsekhmistrenko I need the list of who's going for the recovery

**Comment by auggiemarignier** [comment]
Easiest way to identify deployment vs recovery team is to just write "2021", "2022" or "2021 & 2022" in the content of the person's `md` file

**Comment by mary-tsekhmistrenko** [comment]
Here is the list of participants for both legs

**Leg 1 (3rd - ~21st August; Lisbon - Ponta Delgada):**

Ana Ferreira 				Chief scientist, UCL
Wolfram Geissler			DEPAS pool lead, AWI, Germany
Maria Tsekhmistrenko		UCL and DIAS pool lead, Ireland
Kasra Hosseini		          Alan Turing Institute, UK
Carlos Corela				IDL pool lead, Portugal
Katrina Harris			UCL, UPFLOW PhD student
José Luís Duarte			IDL, Portugal
Alex Saoulis				UCL, PhD student
Dietrich Lange			GEOMAR pool lead, Germany
Roberto Cabieces Diaz		ROA pool lead, Spain
Scientist/technician (TBC)		IPMA, Portugal

**Leg 2 (23rd August - ~8th  September; Ponta Delgada - Lisbon):**

Ana Ferreira			          Chief scientist, UCL
Wolfram Geissler			DEPAS pool lead, AWI, Germany
Maria Tsekhmistrenko		UCL and DIAS pool lead, Ireland
Katrina Harris			UCL, UPFLOW PhD student
Frederik Tilmann		          GFZ, Germany
Frank Krueger		          UoP, Germany
Afonso Loureiro			IDL pool lead, Portugal
Roberto Cabieces Diaz		ROA pool lead, Spain
Steve Hicks				UCL, UK
Kuan-Yu			          GFZ, Germany
Scientist/technician (TBC)		IPMA, Portugal
